enum WindowsEvents {
  GET_CART_ID = 'GET_CART_ID',
  DISPATCH_GET_CART_ID = 'DISPATCH_GET_CART_ID',
  GET_SHOPPING_CART = 'GET_SHOPPING_CART',
  ADD_ITEM_SHOPPING_CART = 'ADD_ITEM_SHOPPING_CART',
  SIMULATE_ADD_PRODUCT = 'SIMULATE_ADD_PRODUCT',
  CART_HEADER = 'CART_HEADER',
  TOGGLE_CART_ASIDE = 'TOGGLE_CART_ASIDE',
  ADD_PRODUCT_IN_CART = 'ADD_PRODUCT_IN_CART',
  ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR',
  UPDATE_SHIPPING_CART = 'UPDATE_SHIPPING_CART',
  GET_SHOPPING_CART_ERROR = 'GET_SHOPPING_CART_ERROR',
  UPDATE_SHOPPING_CART = 'UPDATE_SHOPPING_CART',
}

export default WindowsEvents;
