name: Deploy to k8s
run-name: deploy-to-k8s
on: [push, workflow_dispatch]
jobs:
  unit-test:
    runs-on:
      group: 'gh-runners-self-hosted'

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup Node Version
        uses: actions/setup-node@v4
        with:
          node-version: 18.18

      - name: NPM Commands
        shell: bash
        env:
          GHT_EDS_TOKEN: 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
          BIT_TOKEN: ${{vars.BIT_TOKEN}}
        run: |
          echo $GHT_EDS_TOKEN
          npm config set -- //node-registry.bit.cloud/:_authToken=$BIT_TOKEN
          npm config set -- //npm.pkg.github.com/:_authToken=$GHT_EDS_TOKEN
          npm install
          npm run test

  k8s:
    needs: unit-test
    uses: Cencosud-Cencommerce/actions/.github/workflows/deploy-to-k8s.yml@main
    secrets: inherit
    with:
      dry-run: 'false'
      environment: ${{(github.ref_name == 'master' && 'production') || (github.ref_name == 'uat' && 'uat') || 'staging'}}
